import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";
import { WizardData, Deduction } from "@/types/dispute";

const styles = StyleSheet.create({
  page: {
    padding: 50,
    fontSize: 10,
    fontFamily: "Helvetica",
  },
  title: {
    fontSize: 18,
    fontFamily: "Helvetica-Bold",
    textAlign: "center",
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 12,
    textAlign: "center",
    color: "#666",
    marginBottom: 30,
  },
  propertyInfo: {
    marginBottom: 20,
    padding: 10,
    backgroundColor: "#f9fafb",
  },
  propertyText: {
    fontSize: 10,
    marginBottom: 3,
  },
  table: {
    marginTop: 10,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#1f2937",
    color: "white",
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  tableRowAlt: {
    backgroundColor: "#f9fafb",
  },
  colDescription: {
    width: "25%",
    padding: 8,
    borderRightWidth: 1,
    borderRightColor: "#e5e7eb",
  },
  colAmount: {
    width: "15%",
    padding: 8,
    borderRightWidth: 1,
    borderRightColor: "#e5e7eb",
    textAlign: "right",
  },
  colCategory: {
    width: "15%",
    padding: 8,
    borderRightWidth: 1,
    borderRightColor: "#e5e7eb",
  },
  colDispute: {
    width: "45%",
    padding: 8,
  },
  headerText: {
    fontFamily: "Helvetica-Bold",
    color: "white",
    fontSize: 9,
  },
  cellText: {
    fontSize: 9,
    lineHeight: 1.4,
  },
  cellBold: {
    fontFamily: "Helvetica-Bold",
    fontSize: 9,
  },
  totalRow: {
    flexDirection: "row",
    backgroundColor: "#fef2f2",
    borderTopWidth: 2,
    borderTopColor: "#dc2626",
  },
  totalLabel: {
    width: "25%",
    padding: 8,
    fontFamily: "Helvetica-Bold",
  },
  totalAmount: {
    width: "15%",
    padding: 8,
    fontFamily: "Helvetica-Bold",
    textAlign: "right",
    color: "#dc2626",
  },
  summary: {
    marginTop: 30,
    padding: 15,
    backgroundColor: "#eff6ff",
    borderWidth: 1,
    borderColor: "#3b82f6",
  },
  summaryTitle: {
    fontFamily: "Helvetica-Bold",
    fontSize: 12,
    marginBottom: 10,
    color: "#1d4ed8",
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 5,
  },
  summaryLabel: {
    fontSize: 10,
  },
  summaryValue: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
  },
  summaryTotal: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#3b82f6",
  },
  summaryTotalLabel: {
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
    color: "#1d4ed8",
  },
  summaryTotalValue: {
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
    color: "#15803d",
  },
  noDeductions: {
    textAlign: "center",
    padding: 40,
    color: "#666",
    fontStyle: "italic",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 50,
    right: 50,
    fontSize: 9,
    color: "#666",
    textAlign: "center",
  },
});

interface DeductionsTableProps {
  data: WizardData;
}

function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
  }).format(amount);
}

function getCategoryLabel(category: Deduction["category"]): string {
  const labels: Record<string, string> = {
    cleaning: "Cleaning",
    damage: "Damage",
    unpaid_rent: "Unpaid Rent",
    utilities: "Utilities",
    other: "Other",
  };
  return category ? labels[category] || category : "Unspecified";
}

export function DeductionsTable({ data }: DeductionsTableProps) {
  const depositAmount = data.depositAmount || 0;
  const totalDeductions = data.deductions.reduce((sum, d) => sum + d.amount, 0);
  const amountReceived = data.amountReceived || 0;
  const amountOwed = depositAmount - amountReceived;

  const propertyAddress = `${data.property.address}${data.property.unit ? `, ${data.property.unit}` : ""}, ${data.property.city}, FL ${data.property.zip}`;

  if (data.deductions.length === 0) {
    return (
      <Document>
        <Page size="LETTER" style={styles.page}>
          <Text style={styles.title}>Deductions Dispute Summary</Text>
          <Text style={styles.noDeductions}>
            No itemized deductions were provided by the landlord.{"\n\n"}
            Under Florida Statute 83.49, if the landlord intends to impose a claim on the security deposit, they must provide written notice by certified mail within 30 days of the tenant vacating the premises, specifying the reason for imposing the claim.
          </Text>
          <View style={styles.footer}>
            <Text>Generated by DepositReady.co | This document does not constitute legal advice.</Text>
          </View>
        </Page>
      </Document>
    );
  }

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        {/* Title */}
        <Text style={styles.title}>Deductions Dispute Summary</Text>
        <Text style={styles.subtitle}>Line-by-Line Rebuttal of Claimed Deductions</Text>

        {/* Property Info */}
        <View style={styles.propertyInfo}>
          <Text style={styles.propertyText}>
            <Text style={{ fontFamily: "Helvetica-Bold" }}>Property: </Text>
            {propertyAddress}
          </Text>
          <Text style={styles.propertyText}>
            <Text style={{ fontFamily: "Helvetica-Bold" }}>Landlord: </Text>
            {data.landlord.name}
          </Text>
          <Text style={styles.propertyText}>
            <Text style={{ fontFamily: "Helvetica-Bold" }}>Tenant: </Text>
            {data.tenant.name}
          </Text>
        </View>

        {/* Deductions Table */}
        <View style={styles.table}>
          {/* Header */}
          <View style={styles.tableHeader}>
            <View style={styles.colDescription}>
              <Text style={styles.headerText}>DEDUCTION</Text>
            </View>
            <View style={styles.colAmount}>
              <Text style={styles.headerText}>AMOUNT</Text>
            </View>
            <View style={styles.colCategory}>
              <Text style={styles.headerText}>CATEGORY</Text>
            </View>
            <View style={styles.colDispute}>
              <Text style={styles.headerText}>TENANT{"'"}S DISPUTE</Text>
            </View>
          </View>

          {/* Rows */}
          {data.deductions.map((deduction, index) => (
            <View
              key={index}
              style={[styles.tableRow, index % 2 === 1 ? styles.tableRowAlt : {}]}
            >
              <View style={styles.colDescription}>
                <Text style={styles.cellBold}>{deduction.description}</Text>
              </View>
              <View style={styles.colAmount}>
                <Text style={[styles.cellText, { color: "#dc2626" }]}>
                  {formatCurrency(deduction.amount)}
                </Text>
              </View>
              <View style={styles.colCategory}>
                <Text style={styles.cellText}>
                  {getCategoryLabel(deduction.category)}
                </Text>
              </View>
              <View style={styles.colDispute}>
                <Text style={styles.cellText}>
                  {deduction.dispute || "Disputed - no valid justification provided by landlord."}
                </Text>
              </View>
            </View>
          ))}

          {/* Total Row */}
          <View style={styles.totalRow}>
            <View style={styles.totalLabel}>
              <Text>TOTAL DISPUTED</Text>
            </View>
            <View style={styles.totalAmount}>
              <Text>{formatCurrency(totalDeductions)}</Text>
            </View>
            <View style={styles.colCategory} />
            <View style={styles.colDispute} />
          </View>
        </View>

        {/* Summary Box */}
        <View style={styles.summary}>
          <Text style={styles.summaryTitle}>Financial Summary</Text>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Original Deposit Paid:</Text>
            <Text style={styles.summaryValue}>{formatCurrency(depositAmount)}</Text>
          </View>
          <View style={styles.summaryRow}>
            <Text style={styles.summaryLabel}>Total Deductions Claimed:</Text>
            <Text style={[styles.summaryValue, { color: "#dc2626" }]}>
              ({formatCurrency(totalDeductions)})
            </Text>
          </View>
          {amountReceived > 0 && (
            <View style={styles.summaryRow}>
              <Text style={styles.summaryLabel}>Amount Already Received:</Text>
              <Text style={styles.summaryValue}>{formatCurrency(amountReceived)}</Text>
            </View>
          )}
          <View style={styles.summaryTotal}>
            <Text style={styles.summaryTotalLabel}>Amount Owed to Tenant:</Text>
            <Text style={styles.summaryTotalValue}>{formatCurrency(amountOwed)}</Text>
          </View>
        </View>

        {/* Footer */}
        <View style={styles.footer}>
          <Text>Generated by DepositReady.co | This document does not constitute legal advice.</Text>
        </View>
      </Page>
    </Document>
  );
}
